# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='packet.proto',
  package='',
  serialized_pb=_b('\n\x0cpacket.proto\"\xe0\x02\n\x06Packet\x12\x1a\n\x04type\x18\x01 \x02(\x0e\x32\x0c.Packet.Type\x12 \n\x08lrequest\x18\x02 \x01(\x0b\x32\x0e.login_request\x12\x1c\n\x06lreply\x18\x03 \x01(\x0b\x32\x0c.login_reply\x12!\n\x08srequest\x18\x04 \x01(\x0b\x32\x0f.secure_request\x12\x1d\n\x06sreply\x18\x05 \x01(\x0b\x32\r.secure_reply\x12!\n\x08xrequest\x18\x06 \x01(\x0b\x32\x0f.xnaddr_request\x12\x1d\n\x06xreply\x18\x07 \x01(\x0b\x32\r.xnaddr_reply\"v\n\x04Type\x12\x11\n\rlogin_request\x10\x02\x12\x0f\n\x0blogin_reply\x10\x03\x12\x12\n\x0esecure_request\x10\x04\x12\x10\n\x0csecure_reply\x10\x05\x12\x12\n\x0exnaddr_request\x10\x06\x12\x10\n\x0cxnaddr_reply\x10\x07\"2\n\rlogin_request\x12\x13\n\x0blogin_token\x18\x01 \x02(\x0c\x12\x0c\n\x04port\x18\x02 \x02(\r\"\x82\x01\n\x0blogin_reply\x12\x13\n\x0bsecure_addr\x18\x01 \x02(\r\x12\x0e\n\x06xnaddr\x18\x02 \x02(\r\x12\x0c\n\x04port\x18\x03 \x02(\x05\x12\x0e\n\x06\x61\x62\x45net\x18\x04 \x02(\x0c\x12\x10\n\x08\x61\x62Online\x18\x05 \x02(\x0c\x12\x0c\n\x04xuid\x18\x06 \x02(\x03\x12\x10\n\x08username\x18\x07 \x02(\x0c\" \n\x0esecure_request\x12\x0e\n\x06\x61\x62\x45net\x18\x01 \x02(\x0c\"^\n\x0csecure_reply\x12\x0e\n\x06secure\x18\x01 \x02(\r\x12\x0e\n\x06xnaddr\x18\x02 \x02(\r\x12\x0c\n\x04port\x18\x03 \x02(\r\x12\x0e\n\x06\x61\x62\x45net\x18\x04 \x02(\x0c\x12\x10\n\x08\x61\x62Online\x18\x05 \x02(\x0c\" \n\x0exnaddr_request\x12\x0e\n\x06secure\x18\x01 \x02(\r\"N\n\x0cxnaddr_reply\x12\x0e\n\x06xnaddr\x18\x01 \x02(\r\x12\x0c\n\x04port\x18\x02 \x02(\r\x12\x0e\n\x06\x61\x62\x45net\x18\x03 \x02(\x0c\x12\x10\n\x08\x61\x62Online\x18\x04 \x02(\x0c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PACKET_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='Packet.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='login_request', index=0, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='login_reply', index=1, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='secure_request', index=2, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='secure_reply', index=3, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='xnaddr_request', index=4, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='xnaddr_reply', index=5, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=251,
  serialized_end=369,
)
_sym_db.RegisterEnumDescriptor(_PACKET_TYPE)


_PACKET = _descriptor.Descriptor(
  name='Packet',
  full_name='Packet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Packet.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lrequest', full_name='Packet.lrequest', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lreply', full_name='Packet.lreply', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='srequest', full_name='Packet.srequest', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sreply', full_name='Packet.sreply', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xrequest', full_name='Packet.xrequest', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xreply', full_name='Packet.xreply', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PACKET_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=369,
)


_LOGIN_REQUEST = _descriptor.Descriptor(
  name='login_request',
  full_name='login_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='login_token', full_name='login_request.login_token', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='login_request.port', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=371,
  serialized_end=421,
)


_LOGIN_REPLY = _descriptor.Descriptor(
  name='login_reply',
  full_name='login_reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='secure_addr', full_name='login_reply.secure_addr', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xnaddr', full_name='login_reply.xnaddr', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='login_reply.port', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='abEnet', full_name='login_reply.abEnet', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='abOnline', full_name='login_reply.abOnline', index=4,
      number=5, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xuid', full_name='login_reply.xuid', index=5,
      number=6, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='username', full_name='login_reply.username', index=6,
      number=7, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=424,
  serialized_end=554,
)


_SECURE_REQUEST = _descriptor.Descriptor(
  name='secure_request',
  full_name='secure_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='abEnet', full_name='secure_request.abEnet', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=556,
  serialized_end=588,
)


_SECURE_REPLY = _descriptor.Descriptor(
  name='secure_reply',
  full_name='secure_reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='secure', full_name='secure_reply.secure', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xnaddr', full_name='secure_reply.xnaddr', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='secure_reply.port', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='abEnet', full_name='secure_reply.abEnet', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='abOnline', full_name='secure_reply.abOnline', index=4,
      number=5, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=590,
  serialized_end=684,
)


_XNADDR_REQUEST = _descriptor.Descriptor(
  name='xnaddr_request',
  full_name='xnaddr_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='secure', full_name='xnaddr_request.secure', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=686,
  serialized_end=718,
)


_XNADDR_REPLY = _descriptor.Descriptor(
  name='xnaddr_reply',
  full_name='xnaddr_reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='xnaddr', full_name='xnaddr_reply.xnaddr', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='xnaddr_reply.port', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='abEnet', full_name='xnaddr_reply.abEnet', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='abOnline', full_name='xnaddr_reply.abOnline', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=720,
  serialized_end=798,
)

_PACKET.fields_by_name['type'].enum_type = _PACKET_TYPE
_PACKET.fields_by_name['lrequest'].message_type = _LOGIN_REQUEST
_PACKET.fields_by_name['lreply'].message_type = _LOGIN_REPLY
_PACKET.fields_by_name['srequest'].message_type = _SECURE_REQUEST
_PACKET.fields_by_name['sreply'].message_type = _SECURE_REPLY
_PACKET.fields_by_name['xrequest'].message_type = _XNADDR_REQUEST
_PACKET.fields_by_name['xreply'].message_type = _XNADDR_REPLY
_PACKET_TYPE.containing_type = _PACKET
DESCRIPTOR.message_types_by_name['Packet'] = _PACKET
DESCRIPTOR.message_types_by_name['login_request'] = _LOGIN_REQUEST
DESCRIPTOR.message_types_by_name['login_reply'] = _LOGIN_REPLY
DESCRIPTOR.message_types_by_name['secure_request'] = _SECURE_REQUEST
DESCRIPTOR.message_types_by_name['secure_reply'] = _SECURE_REPLY
DESCRIPTOR.message_types_by_name['xnaddr_request'] = _XNADDR_REQUEST
DESCRIPTOR.message_types_by_name['xnaddr_reply'] = _XNADDR_REPLY

Packet = _reflection.GeneratedProtocolMessageType('Packet', (_message.Message,), dict(
  DESCRIPTOR = _PACKET,
  __module__ = 'packet_pb2'
  # @@protoc_insertion_point(class_scope:Packet)
  ))
_sym_db.RegisterMessage(Packet)

login_request = _reflection.GeneratedProtocolMessageType('login_request', (_message.Message,), dict(
  DESCRIPTOR = _LOGIN_REQUEST,
  __module__ = 'packet_pb2'
  # @@protoc_insertion_point(class_scope:login_request)
  ))
_sym_db.RegisterMessage(login_request)

login_reply = _reflection.GeneratedProtocolMessageType('login_reply', (_message.Message,), dict(
  DESCRIPTOR = _LOGIN_REPLY,
  __module__ = 'packet_pb2'
  # @@protoc_insertion_point(class_scope:login_reply)
  ))
_sym_db.RegisterMessage(login_reply)

secure_request = _reflection.GeneratedProtocolMessageType('secure_request', (_message.Message,), dict(
  DESCRIPTOR = _SECURE_REQUEST,
  __module__ = 'packet_pb2'
  # @@protoc_insertion_point(class_scope:secure_request)
  ))
_sym_db.RegisterMessage(secure_request)

secure_reply = _reflection.GeneratedProtocolMessageType('secure_reply', (_message.Message,), dict(
  DESCRIPTOR = _SECURE_REPLY,
  __module__ = 'packet_pb2'
  # @@protoc_insertion_point(class_scope:secure_reply)
  ))
_sym_db.RegisterMessage(secure_reply)

xnaddr_request = _reflection.GeneratedProtocolMessageType('xnaddr_request', (_message.Message,), dict(
  DESCRIPTOR = _XNADDR_REQUEST,
  __module__ = 'packet_pb2'
  # @@protoc_insertion_point(class_scope:xnaddr_request)
  ))
_sym_db.RegisterMessage(xnaddr_request)

xnaddr_reply = _reflection.GeneratedProtocolMessageType('xnaddr_reply', (_message.Message,), dict(
  DESCRIPTOR = _XNADDR_REPLY,
  __module__ = 'packet_pb2'
  # @@protoc_insertion_point(class_scope:xnaddr_reply)
  ))
_sym_db.RegisterMessage(xnaddr_reply)


# @@protoc_insertion_point(module_scope)
